### ISSUE TITLE
Street number results sort order-1000s come before 200s

### ISSUE THREAD

**Issue by EveSnyder** [historyforge/historyforge-old#74]
Could you change the street number results sort order so that it goes ascending or descending instead of capturing any number that starts with 1 before going to all the numbers that start with 2.

**Comment by dfurber** [comment]
I think I fixed it- please check.

**Comment by EveSnyder** [comment]
Not fixed.  It also includes both East and West or North and South instead of the specified prefix.
